name: CI/CD Backend Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK 18
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18

    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Gradle Build
      uses: gradle/gradle-build-action@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker Image
      run: docker build -t dockerknet/backend-app:latest .
      working-directory: ./ueK223_backend_2-main

    # Push Docker image to Docker Hub
    - name: Push Docker Image
      run: docker push dockerknet/backend-app:latest
    
deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
  - name: Deploy to remote server
    uses: appleboy/ssh-action@v0.1.4
    with:
      host: ${{ secrets.SERVER_HOST }}
      username: ${{ secrets.SERVER_USERNAME }}
      password: ${{ secrets.SERVER_PASSWORD }}
      port: 22
      script: |
        pwd
        ls
        ./deploy.sh
